import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

REPO_ROOT = Path(__file__).resolve().parent.parent
BENCHMARKS_DIR = REPO_ROOT / "benchmarks"
CHARTS_DIR = BENCHMARKS_DIR / "charts"

sys.path.insert(0, str(REPO_ROOT / "scripts"))


def _run_benchmarks_fresh() -> None:
    import run_baseline
    import run_bfp_benchmark
    import run_kvcache_benchmark
    import run_combined_benchmark

    print("running run_baseline.main() ...")
    run_baseline.main()
    print("running run_bfp_benchmark.main() ...")
    run_bfp_benchmark.main()
    print("running run_kvcache_benchmark.main() ...")
    run_kvcache_benchmark.main()
    print("running run_combined_benchmark.main() ...")
    run_combined_benchmark.main()


def _load(name: str) -> dict:
    return json.loads((BENCHMARKS_DIR / name).read_text())


def _chart_bfp_breakpoint() -> None:
    short_baseline = _load("baseline_results.json")["summary"]
    short_bfp = _load("bfp_results.json")["summary"]
    long_baseline = _load("baseline_results_longprompt.json")["summary"]
    long_bfp = _load("bfp_results_longprompt.json")["summary"]

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    for ax, label, baseline, bfp in (
        (axes[0], "short prompt", short_baseline, short_bfp),
        (axes[1], "long prompt", long_baseline, long_bfp),
    ):
        metrics = ["prefill_tokens_per_sec", "decode_tokens_per_sec"]
        x = range(len(metrics))
        baseline_vals = [baseline[m]["median"] for m in metrics]
        bfp_vals = [bfp[m]["median"] for m in metrics]
        width = 0.35
        ax.bar([i - width / 2 for i in x], baseline_vals, width, label="fp32")
        ax.bar([i + width / 2 for i in x], bfp_vals, width, label="BFP")
        ax.set_xticks(list(x))
        ax.set_xticklabels(["prefill tok/s", "decode tok/s"])
        ax.set_title(label)
        ax.legend()
    fig.suptitle("BFP break point: helps prefill, costs less at decode")
    fig.tight_layout()
    fig.savefig(CHARTS_DIR / "bfp_breakpoint.png", dpi=150)
    plt.close(fig)


def _chart_cache_hit_rate_vs_speedup() -> None:
    data = _load("kvcache_results.json")
    names = list(data.keys())
    hit_rates = [data[n]["avg_hit_rate"] for n in names]
    speedups = [data[n]["avg_honest_prefill_speedup"] for n in names]

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.scatter(hit_rates, speedups)
    for name, x, y in zip(names, hit_rates, speedups):
        ax.annotate(name, (x, y), textcoords="offset points", xytext=(5, 5))
    ax.axhline(1.0, color="gray", linestyle="--", linewidth=1)
    ax.set_xlabel("avg hit rate")
    ax.set_ylabel("avg honest prefill speedup")
    ax.set_title("KV-cache: hit rate vs. honest prefill speedup")
    fig.tight_layout()
    fig.savefig(CHARTS_DIR / "cache_hit_rate_vs_speedup.png", dpi=150)
    plt.close(fig)


def _chart_combined() -> None:
    data = _load("combined_results.json")
    prompt_sets = [k for k in data.keys() if k != "provenance"]
    combos = ["fp32_no_cache", "fp32_cache", "bfp_no_cache", "bfp_cache"]

    fig, ax = plt.subplots(figsize=(8, 5))
    width = 0.2
    x = range(len(prompt_sets))
    for i, combo in enumerate(combos):
        vals = [data[ps][combo]["total_honest_prefill_seconds"] for ps in prompt_sets]
        offset = (i - 1.5) * width
        ax.bar([xi + offset for xi in x], vals, width, label=combo)
    ax.set_xticks(list(x))
    ax.set_xticklabels(prompt_sets)
    ax.set_ylabel("total honest prefill seconds (5 prompts)")
    ax.set_title("Combined pipeline: all 4 toggle states x 3 prompt sets")
    ax.legend()
    fig.tight_layout()
    fig.savefig(CHARTS_DIR / "combined_comparison.png", dpi=150)
    plt.close(fig)


def _write_summary_md() -> None:
    baseline = _load("baseline_results.json")["summary"]
    bfp = _load("bfp_results.json")["summary"]
    kvcache = _load("kvcache_results.json")
    combined = _load("combined_results.json")

    lines = ["# Slide chart data (generated by scripts/export_slide_charts.py)", ""]
    lines.append("## BFP break point (short prompt)")
    lines.append("| | prefill tok/s | decode tok/s |")
    lines.append("|---|---:|---:|")
    lines.append(f"| fp32 | {baseline['prefill_tokens_per_sec']['median']:.1f} | {baseline['decode_tokens_per_sec']['median']:.1f} |")
    lines.append(f"| BFP | {bfp['prefill_tokens_per_sec']['median']:.1f} | {bfp['decode_tokens_per_sec']['median']:.1f} |")
    lines.append("")
    lines.append("## KV-cache hit rate vs. honest prefill speedup")
    lines.append("| prompt set | avg hit rate | avg honest prefill speedup |")
    lines.append("|---|---:|---:|")
    for name, row in kvcache.items():
        lines.append(f"| {name} | {row['avg_hit_rate']:.3f} | {row['avg_honest_prefill_speedup']:.3f} |")
    lines.append("")
    lines.append("## Combined pipeline: total honest prefill seconds")
    lines.append("| prompt set | fp32_no_cache | fp32_cache | bfp_no_cache | bfp_cache |")
    lines.append("|---|---:|---:|---:|---:|")
    for ps, combos in combined.items():
        if ps == "provenance":
            continue
        row = [f"{combos[c]['total_honest_prefill_seconds']:.3f}" for c in ("fp32_no_cache", "fp32_cache", "bfp_no_cache", "bfp_cache")]
        lines.append(f"| {ps} | " + " | ".join(row) + " |")

    (CHARTS_DIR / "summary.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    _run_benchmarks_fresh()
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    _chart_bfp_breakpoint()
    _chart_cache_hit_rate_vs_speedup()
    _chart_combined()
    _write_summary_md()
    print(f"wrote charts + summary.md to {CHARTS_DIR}")


if __name__ == "__main__":
    main()
